name: Run Pytest
on: [push, pull_request]

jobs:
  run-unit-tests:
    environment: env
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    env:
      MONGO_DB: ${{ secrets.MONGO_DB }}
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps: 
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" 
      - name: Build Docker Image
        run: |
          docker build -t test-image -f PytestDockerfile .
      - name: Run Dockerized Unit Tests
        run: |
          docker run -e MONGO_DB=$MONGO_DB -e MONGO_URI=$MONGO_URI --network host test-image
            
            
