name: Run Pytest
on: [push, pull_request]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps: 
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" 
      - name: Build Docker Image
        run: |
          docker build -t test-image -f PytestDockerfile .
      - name: Run Dockerized Unit Tests
        run: |
          docker run --network host test-image
            
            